### ISSUE TITLE
Postgres template encoding

### ISSUE THREAD

**Issue by chicocvenancio** [Trust-Code/trust-docker#2]
Obrigado pelo trabalho de setup do Docker.
Usando o trustcode/trustcode_odoo:latest ainda recebo o erro de enconding do template1 ao tentar criar uma base no Odoo.
Nada que não seja facilmente resolvido, mas eu suponho que esse trabalho possa ser automatizado.

A quem enfrentar o problema o https://www.odoo.com/forum/help-1/question/dataerror-new-encoding-utf8-is-incompatible-with-the-encoding-of-the-template-database-sql-ascii-52124 tem a solução.

**Comment by danimaribeiro** [comment]
Corrigido https://github.com/Trust-Code/trust-docker/commit/1fd4db5af32cf8eecbe3c36e2d39dbc4287c3763
